stages:
- name: Create Build Tag
  steps:
  - runScriptConfig:
      image: jgreat/drone-build-tag:0.1.0
      shellScript: build-tags.sh --include-feature-tag
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jgreat/vote-demo-web:use-tags-file
      pushRemote: true
      registry: index.docker.io
- name: Render and Publish Helm Charts
  steps:
  - runScriptConfig:
      image: jgreat/helm-with-plugins:v2.11.0
      shellScript: ./scripts/publish-charts.sh
    env:
      CHART_NAME: '${CICD_GIT_BRANCH}'
      HELM_REPO_NAME: '${CICD_GIT_REPO}'
      HELM_REPO_URL: 'https://vote-demo-charts.eng.rancher.space/${CICD_GIT_REPO}/'
    envFrom:
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_PASS
      targetKey: CHART_REPO_PASSWORD
    - sourceName: chart-creds
      sourceKey: BASIC_AUTH_USER
      targetKey: HELM_REPO_USERNAME

timeout: 10