stages:
- name: Create Build Tag
  steps:
  - runScriptConfig:
      image: jgreat/drone-build-tag:0.0.2
      shellScript: build-tags.sh
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jgreat/vote-demo-web:no-tag
      pushRemote: true
      registry: index.docker.io
      env:
        PLUGIN_ENV_FILE: .env

timeout: 10